portas = [
    ("PROJETO SEM IMAGEM"),
    ("PORTA PIVOTANTE"),
    ("PORTA PIVOTANTE 1 FIXO"),
    ("PORTA PIVOTANTE 2 FOLHAS"),
    ("PORTA PIVOTANTE 2 FOLHAS 2 FIXO"),
    ("PORTA PIVOTANTE 1 FIXO 1 BANDEIRA"),
    ("PORTA PIVOTANTE"),
    ("PORTA PIVOTANTE"),
    ("PORTA PIVOTANTE"),
    ("PORTA PIVOTANTE"),
    ("PORTA PIVOTANTE"),
    ("PORTA PIVOTANTE")

]
janelas = [
    ("PROJETO SEM IMAGEM"),
    ("JANELA 1 FOLHA MOVEL 1 FIXO"),
    ("JANELA 2 FOLHAS MOVEL"),
    ("JANELA 2 FOLHA MOVEL 1 FIXA")
]