# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GIT_PDV/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(712, 587)
        Login.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Login.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0847458, y1:0.04, x2:0.788, y2:0.897727, stop:0.152542 rgba(17, 184, 255, 255), stop:0.988701 rgba(14, 124, 157, 255))")
        self.btn_login = QtWidgets.QPushButton(Login)
        self.btn_login.setGeometry(QtCore.QRect(250, 410, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("background-color:rgb(0, 4, 76);\n"
"color:white;")
        self.btn_login.setObjectName("btn_login")
        self.senha = QtWidgets.QLineEdit(Login)
        self.senha.setGeometry(QtCore.QRect(230, 355, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.senha.setFont(font)
        self.senha.setStyleSheet("border:0;\n"
"background:transparent;")
        self.senha.setInputMethodHints(QtCore.Qt.ImhNone)
        self.senha.setObjectName("senha")
        self.lock = QtWidgets.QLabel(Login)
        self.lock.setGeometry(QtCore.QRect(200, 360, 21, 16))
        self.lock.setStyleSheet("background:transparent;")
        self.lock.setText("")
        self.lock.setPixmap(QtGui.QPixmap("GIT_PDV\\../../../Desktop/icons/lock_resized.png"))
        self.lock.setObjectName("lock")
        self.line = QtWidgets.QFrame(Login)
        self.line.setGeometry(QtCore.QRect(200, 320, 261, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setStyleSheet("color:rgb(29, 78, 255);\n"
"background:transparent;")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.user = QtWidgets.QLineEdit(Login)
        self.user.setGeometry(QtCore.QRect(230, 305, 231, 21))
        self.user.setStyleSheet("border:0;\n"
"background:transparent;\n"
"")
        self.user.setText("")
        self.user.setObjectName("user")
        self.letter = QtWidgets.QLabel(Login)
        self.letter.setGeometry(QtCore.QRect(200, 310, 21, 21))
        self.letter.setStyleSheet("background:transparent;")
        self.letter.setText("")
        self.letter.setPixmap(QtGui.QPixmap("GIT_PDV\\../../../Desktop/icons/letter_resized.png"))
        self.letter.setObjectName("letter")
        self.line_2 = QtWidgets.QFrame(Login)
        self.line_2.setGeometry(QtCore.QRect(200, 380, 261, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("color:rgb(29, 78, 255);\n"
"background:transparent;")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(270, 160, 141, 131))
        self.label_3.setStyleSheet("background:transparent;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("GIT_PDV\\../../../Desktop/icons/user.png"))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.btn_login.setText(_translate("Login", "LOGIN"))
        self.senha.setPlaceholderText(_translate("Login", "Password"))
        self.user.setPlaceholderText(_translate("Login", "User ID"))
